name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk

  flutter_localizations:
    sdk: flutter

  flutter_native_splash: ^2.4.5
  flip_card: ^0.7.0
  google_fonts: ^6.2.1
  english_words: ^4.0.0
  provider: ^6.0.0
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.15
  http: ^1.2.2 
  shared_preferences: ^2.1.1
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2
  universal_html: ^2.2.4
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  flutter_secure_storage: ^9.2.4
  iconify_flutter: ^0.0.7
  get: ^4.6.6
  test: ^1.25.15
  stock: ^1.1.2

dependency_overrides:
  intl: any

dev_dependencies:
  test_api: ^0.7.3

  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  intl: ^0.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/